//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomFieldSettings) DeepCopyInto(out *CustomFieldSettings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomFieldSettings.
func (in *CustomFieldSettings) DeepCopy() *CustomFieldSettings {
	if in == nil {
		return nil
	}
	out := new(CustomFieldSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JitRequest) DeepCopyInto(out *JitRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JitRequest.
func (in *JitRequest) DeepCopy() *JitRequest {
	if in == nil {
		return nil
	}
	out := new(JitRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JitRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JitRequestList) DeepCopyInto(out *JitRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JitRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JitRequestList.
func (in *JitRequestList) DeepCopy() *JitRequestList {
	if in == nil {
		return nil
	}
	out := new(JitRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JitRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JitRequestSpec) DeepCopyInto(out *JitRequestSpec) {
	*out = *in
	if in.AdditionUserEmails != nil {
		in, out := &in.AdditionUserEmails, &out.AdditionUserEmails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.EndTime.DeepCopyInto(&out.EndTime)
	if in.JiraFields != nil {
		in, out := &in.JiraFields, &out.JiraFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JitRequestSpec.
func (in *JitRequestSpec) DeepCopy() *JitRequestSpec {
	if in == nil {
		return nil
	}
	out := new(JitRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JitRequestStatus) DeepCopyInto(out *JitRequestStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JitRequestStatus.
func (in *JitRequestStatus) DeepCopy() *JitRequestStatus {
	if in == nil {
		return nil
	}
	out := new(JitRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JustInTimeConfig) DeepCopyInto(out *JustInTimeConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JustInTimeConfig.
func (in *JustInTimeConfig) DeepCopy() *JustInTimeConfig {
	if in == nil {
		return nil
	}
	out := new(JustInTimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JustInTimeConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JustInTimeConfigList) DeepCopyInto(out *JustInTimeConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JustInTimeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JustInTimeConfigList.
func (in *JustInTimeConfigList) DeepCopy() *JustInTimeConfigList {
	if in == nil {
		return nil
	}
	out := new(JustInTimeConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JustInTimeConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JustInTimeConfigSpec) DeepCopyInto(out *JustInTimeConfigSpec) {
	*out = *in
	if in.AllowedClusterRoles != nil {
		in, out := &in.AllowedClusterRoles, &out.AllowedClusterRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredFields != nil {
		in, out := &in.RequiredFields, &out.RequiredFields
		*out = new(RequiredFieldsSpec)
		**out = **in
	}
	if in.CustomFields != nil {
		in, out := &in.CustomFields, &out.CustomFields
		*out = make(map[string]CustomFieldSettings, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JustInTimeConfigSpec.
func (in *JustInTimeConfigSpec) DeepCopy() *JustInTimeConfigSpec {
	if in == nil {
		return nil
	}
	out := new(JustInTimeConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JustInTimeConfigStatus) DeepCopyInto(out *JustInTimeConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JustInTimeConfigStatus.
func (in *JustInTimeConfigStatus) DeepCopy() *JustInTimeConfigStatus {
	if in == nil {
		return nil
	}
	out := new(JustInTimeConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredFieldsSpec) DeepCopyInto(out *RequiredFieldsSpec) {
	*out = *in
	out.ClusterRole = in.ClusterRole
	out.StartTime = in.StartTime
	out.EndTime = in.EndTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredFieldsSpec.
func (in *RequiredFieldsSpec) DeepCopy() *RequiredFieldsSpec {
	if in == nil {
		return nil
	}
	out := new(RequiredFieldsSpec)
	in.DeepCopyInto(out)
	return out
}
