apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jira-jit-rbac-operator.fullname" . }}-jitrequest-viewer-role
  labels:
  {{- include "jira-jit-rbac-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - justintime.samir.io
  resources:
  - jitrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - justintime.samir.io
  resources:
  - jitrequests/status
  verbs:
  - get