apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "jira-jit-rbac-operator.fullname" . }}-justintimeconfig-viewer-role
  labels:
  {{- include "jira-jit-rbac-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - justintime.samir.io
  resources:
  - justintimeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - justintime.samir.io
  resources:
  - justintimeconfigs/status
  verbs:
  - get