apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jira-jit-rbac-operator.fullname" . }}-manager-admin-rolebinding
  labels:
  {{- include "jira-jit-rbac-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: '{{ include "jira-jit-rbac-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'