{{- if .Values.webhook.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "jira-jit-rbac-operator.fullname" . }}-metrics-certs
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
  labels:
  {{- include "jira-jit-rbac-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "jira-jit-rbac-operator.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc'
  - '{{ include "jira-jit-rbac-operator.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "jira-jit-rbac-operator.fullname" . }}-selfsigned-issuer'
  secretName: metrics-server-cert
{{- end }}