{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "jira-jit-rbac-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "jira-jit-rbac-operator.fullname" . }}-serving-cert
  labels:
  {{- include "jira-jit-rbac-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "jira-jit-rbac-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-justintime-samir-io-v1-jitrequest
  failurePolicy: Fail
  name: vjitrequest-v1.kb.io
  rules:
  - apiGroups:
    - justintime.samir.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jitrequests
  sideEffects: None
{{- end }}