# permissions for end users to edit jitrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jit-rbac-operator
    app.kubernetes.io/managed-by: kustomize
  name: jitrequest-editor-role
rules:
- apiGroups:
  - justintime.samir.io
  resources:
  - jitrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - justintime.samir.io
  resources:
  - jitrequests/status
  verbs:
  - get
