# permissions for end users to view jitrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jira-jit-rbac-operator
    app.kubernetes.io/managed-by: kustomize
  name: jitrequest-viewer-role
rules:
- apiGroups:
  - justintime.samir.io
  resources:
  - jitrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - justintime.samir.io
  resources:
  - jitrequests/status
  verbs:
  - get
