# permissions for end users to edit justintimeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jira-jit-rbac-operator
    app.kubernetes.io/managed-by: kustomize
  name: justintimeconfig-editor-role
rules:
- apiGroups:
  - justintime.samir.io
  resources:
  - justintimeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - justintime.samir.io
  resources:
  - justintimeconfigs/status
  verbs:
  - get
