# permissions for end users to view justintimeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jit-rbac-operator
    app.kubernetes.io/managed-by: kustomize
  name: justintimeconfig-viewer-role
rules:
- apiGroups:
  - justintime.samir.io
  resources:
  - justintimeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - justintime.samir.io
  resources:
  - justintimeconfigs/status
  verbs:
  - get
