---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - justintime.samir.io
  resources:
  - justintimeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - justintime.samir.io
  resources:
  - justintimeconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - justintime.samir.io
  resources:
  - justintimeconfigs/status
  verbs:
  - get
  - patch
  - update
