apiVersion: justintime.samir.io/v1
kind: JustInTimeConfig
metadata:
  name: jira-jit-rbac-operator-default
spec:
  allowedClusterRoles:
    - admin
    - edit
  labels:
    - minikube-test
  environment:
    environment: local
    cluster: minikube
  additionalCommentText: "cluster: minikube"
  workflowApprovedStatus: "Approved"
  rejectedTransitionID: "21"
  jiraProject: IAM
  jiraIssueType: Access Request
  approvedTransitionID: "41"
  requiredFields:
    ClusterRole:
      type: "select"
      jiraCustomField: "customfield_10115"
    StartTime:
      type: "date"
      jiraCustomField: "customfield_10200"
    EndTime:
      type: "date"
      jiraCustomField: "customfield_10201"
  customFields:
    Approver:
      type: "user"
      jiraCustomField: "customfield_10112"
    ProductOwner:
      type: "user"
      jiraCustomField: "customfield_10113"
    Justification:
      type: "text"
      jiraCustomField: "customfield_10114"
