apiVersion: justintime.samir.io/v1
kind: JitRequest
metadata:
  name: jitrequest-sample
spec:
  reporter: test@foo.com
  clusterRole: edit
  approver: samirtahir91
  productOwner: samirtahir91
  justification: "need a jit now pls"
  namespace: foo
  startTime: 2024-12-09T14:31:00Z
  endTime: 2024-12-09T14:31:10Z
---
# apiVersion: justintime.samir.io/v1
# kind: JustInTimeConfig
# metadata:
#   name: jira-jit-rbac-operator-default
# spec:
#   allowedClusterRoles:
#   - admin
#   - edit
#   - bigting
