apiVersion: justintime.samir.io/v1
kind: JitRequest
metadata:
  name: jitrequest-sample
spec:
  userID: test@foo.com
  namespace: foo
  startTime: 2025-01-15T16:08:00Z
  endTime: 2025-01-15T16:09:10Z
  clusterRole: edit
  jiraFields:
    Approver: admin
    ProductOwner: admin
    Justification: "need a jit now pls"
