apiVersion: justintime.samir.io/v1
kind: JitRequest
metadata:
  name: jitrequest-sample
spec:
  userEmail: dev@dev.com
  additionalEmails:
    - "dev2@dev.com"
    - "dev3@dev.com"
  namespaces: 
    - foo
  startTime: 2025-01-17T09:27:10Z
  endTime: 2025-01-17T09:28:10Z
  clusterRole: edit
  jiraFields:
    Approver: admin
    ProductOwner: admin
    Justification: "need a jit now pls"
